package praktomatTask1;

import java.io.*;import java.lang.*;import java.util.*;@SuppressWarnings("unchecked")
public class TOH{static int iLikeToMoveItMoveItAndRegister=0;static int adaadAwal=0;static int adaadTani=0;static int adaadTalet=0;static public Stack<Integer>Wahad=new Stack<Integer>();static public Stack<Integer>Ithnein=new Stack<Integer>();static public Stack<Integer>Thalatha=new Stack<Integer>();public static void main(String[]params){try{int aktarMinHeikMostaheel=0;String insertCoinHere=params[0];iLikeToMoveItMoveItAndRegister=0;aktarMinHeikMostaheel=Integer.parseInt(insertCoinHere);if(aktarMinHeikMostaheel<2||aktarMinHeikMostaheel>9){System.out.println("Enter between 2 - 9");return;}
for(int i=aktarMinHeikMostaheel;i>=1;i--){Wahad.push(i);}
adaadAwal=Wahad.size();adaadTani=Ithnein.size();adaadTalet=Thalatha.size();iAmResposibleForTheCLIStuff();dealWithMeIfYouWantToCompleteTheTowerOfHanoi(aktarMinHeikMostaheel,Wahad,Ithnein,Thalatha);System.out.println("Total Moves = "+iLikeToMoveItMoveItAndRegister);while(Thalatha.size()>0){Thalatha.pop();}}catch(Exception ghaltaaaaaa){ghaltaaaaaa.printStackTrace();}}
static public void MatbaaFakhreh(Stack<Integer>s){System.out.print(s.toString());}
static public void iWouldLikeYouToDealWithThisSimplerCase(Stack<Integer>pleaseStartWithMe,Stack<Integer>pleaseHaveCoffeeWithMe,Stack<Integer>pleaseEndWithMe){pleaseHaveCoffeeWithMe.push(pleaseStartWithMe.pop());iLikeToMoveItMoveItAndRegister++;iAmResposibleForTheCLIStuff();pleaseEndWithMe.push(pleaseStartWithMe.pop());iLikeToMoveItMoveItAndRegister++;iAmResposibleForTheCLIStuff();pleaseEndWithMe.push(pleaseHaveCoffeeWithMe.pop());iLikeToMoveItMoveItAndRegister++;iAmResposibleForTheCLIStuff();}
static public int dealWithMeIfYouWantToCompleteTheTowerOfHanoi(int raqamIlAqras,Stack<Integer>pleaseStartWithMe,Stack<Integer>pleaseHaveCoffeeWithMe,Stack<Integer>pleaseEndWithMe){if(raqamIlAqras<=4){if((raqamIlAqras%2)==0){iWouldLikeYouToDealWithThisSimplerCase(pleaseStartWithMe,pleaseHaveCoffeeWithMe,pleaseEndWithMe);raqamIlAqras=raqamIlAqras-1;if(raqamIlAqras==1){return 1;}
pleaseHaveCoffeeWithMe.push(pleaseStartWithMe.pop());iLikeToMoveItMoveItAndRegister++;iAmResposibleForTheCLIStuff();iWouldLikeYouToDealWithThisSimplerCase(pleaseEndWithMe,pleaseStartWithMe,pleaseHaveCoffeeWithMe);pleaseEndWithMe.push(pleaseStartWithMe.pop());iLikeToMoveItMoveItAndRegister++;iAmResposibleForTheCLIStuff();dealWithMeIfYouWantToCompleteTheTowerOfHanoi(raqamIlAqras,pleaseHaveCoffeeWithMe,pleaseStartWithMe,pleaseEndWithMe);}else{if(raqamIlAqras==1){return-1;}
iWouldLikeYouToDealWithThisSimplerCase(pleaseStartWithMe,pleaseEndWithMe,pleaseHaveCoffeeWithMe);raqamIlAqras=raqamIlAqras-1;pleaseEndWithMe.push(pleaseStartWithMe.pop());iLikeToMoveItMoveItAndRegister++;iAmResposibleForTheCLIStuff();iWouldLikeYouToDealWithThisSimplerCase(pleaseHaveCoffeeWithMe,pleaseStartWithMe,pleaseEndWithMe);}
return 1;}else if(raqamIlAqras>=5){dealWithMeIfYouWantToCompleteTheTowerOfHanoi(raqamIlAqras-2,pleaseStartWithMe,pleaseHaveCoffeeWithMe,pleaseEndWithMe);pleaseHaveCoffeeWithMe.push(pleaseStartWithMe.pop());iLikeToMoveItMoveItAndRegister++;iAmResposibleForTheCLIStuff();dealWithMeIfYouWantToCompleteTheTowerOfHanoi(raqamIlAqras-2,pleaseEndWithMe,pleaseStartWithMe,pleaseHaveCoffeeWithMe);pleaseEndWithMe.push(pleaseStartWithMe.pop());iLikeToMoveItMoveItAndRegister++;iAmResposibleForTheCLIStuff();dealWithMeIfYouWantToCompleteTheTowerOfHanoi(raqamIlAqras-1,pleaseHaveCoffeeWithMe,pleaseStartWithMe,pleaseEndWithMe);}
return 1;}
static public void iAmResposibleForTheCLIStuff(){if(adaadAwal!=Wahad.size()||adaadTani!=Ithnein.size()||adaadTalet!=Thalatha.size()){int fareqWahad=Wahad.size()-adaadAwal;int fareqTani=Ithnein.size()-adaadTani;int fareqTalet=Thalatha.size()-adaadTalet;if(fareqWahad==1){if(fareqTani==-1){System.out.print("Move Disc "+Wahad.peek()+" From B To A");}else{System.out.print("Move Disc "+Wahad.peek()+" From C To A");}}else if(fareqTani==1){if(fareqWahad==-1){System.out.print("Move Disc "+Ithnein.peek()+" From A To B");}else{System.out.print("Move Disc "+Ithnein.peek()+" From C To B");}}else{if(fareqWahad==-1){System.out.print("Move Disc "+Thalatha.peek()+" From A To C");}else{System.out.print("Move Disc "+Thalatha.peek()+" From B To C");}}
adaadAwal=Wahad.size();adaadTani=Ithnein.size();adaadTalet=Thalatha.size();System.out.println();}
MatbaaFakhreh(Wahad);System.out.print(" , ");MatbaaFakhreh(Ithnein);System.out.print(" , ");MatbaaFakhreh(Thalatha);System.out.print(" , ");}}
